In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as plt

In [3]:
data_set = pd.read_csv("E:\SAIF\prwatech\ml\Datasets\Test_Dataset\SUV_predict.csv")

In [4]:
X = data_set.iloc[:,[2,3]].values

In [6]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [7]:
y = data_set.iloc[:,[4]].values

In [8]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=200)

In [39]:
X_test

array([[ 3.61861444e-01, -4.58699305e-01],
       [ 1.11378133e+00, -1.16321243e+00],
       [-1.08088483e-01, -9.11272408e-02],
       [ 1.95969120e+00,  1.07285096e+00],
       [ 4.55851429e-01, -6.04962355e-02],
       [-3.90058440e-01,  9.26587911e-02],
       [ 2.67871458e-01,  2.76444823e-01],
       [ 8.31811371e-01, -2.13651262e-01],
       [-1.04798834e+00, -1.04068841e+00],
       [ 1.01979134e+00,  1.62420906e+00],
       [-1.40984978e-02,  2.45124620e+00],
       [-1.23596831e+00, -3.36175283e-01],
       [-1.08088483e-01,  1.01158895e+00],
       [-1.08088483e-01, -4.89330310e-01],
       [ 7.98914876e-02, -4.58699305e-01],
       [-1.08088483e-01, -1.01005740e+00],
       [-2.02078469e-01, -2.13651262e-01],
       [-1.32995829e+00, -5.50592321e-01],
       [ 9.25801356e-01, -7.03747347e-01],
       [ 1.86570121e+00, -1.83020257e-01],
       [ 2.67871458e-01, -1.52389251e-01],
       [ 6.43831400e-01, -8.26271368e-01],
       [ 3.61861444e-01, -1.10195042e+00],
       [ 2.

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()

In [20]:
X_train = sc.fit_transform(X_train)
X_train

C:\Users\SAIF04KHAN\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\SAIF04KHAN\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 2.67871458e-01, -1.83020257e-01],
       [-2.02078469e-01,  2.15182812e-01],
       [-1.08088483e-01, -3.66806289e-01],
       [ 1.11378133e+00, -1.16321243e+00],
       [ 2.05368118e+00, -1.13258142e+00],
       [-9.53998352e-01,  6.74647892e-01],
       [ 2.67871458e-01, -2.98652302e-02],
       [-7.66018381e-01,  4.29599850e-01],
       [-1.04798834e+00, -9.48795390e-01],
       [ 1.01979134e+00,  9.19695935e-01],
       [ 1.01979134e+00, -9.48795390e-01],
       [ 1.30176130e+00,  2.08367414e+00],
       [ 1.77171123e+00,  2.05304313e+00],
       [-1.40984978e-02,  1.53920802e-01],
       [ 8.31811371e-01,  2.45813818e-01],
       [ 7.98914876e-02, -1.52389251e-01],
       [-2.96068454e-01,  1.50168504e+00],
       [-2.96068454e-01,  1.40979202e+00],
       [-9.53998352e-01, -2.44282267e-01],
       [-3.90058440e-01, -1.16321243e+00],
       [ 2.67871458e-01, -2.74913273e-01],
       [-4.84048425e-01,  6.13385881e-01],
       [ 1.39575128e+00,  2.20619816e+00],
       [-5.

In [21]:
X_test = sc.transform(X_test)
X_test

C:\Users\SAIF04KHAN\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 3.61861444e-01, -4.58699305e-01],
       [ 1.11378133e+00, -1.16321243e+00],
       [-1.08088483e-01, -9.11272408e-02],
       [ 1.95969120e+00,  1.07285096e+00],
       [ 4.55851429e-01, -6.04962355e-02],
       [-3.90058440e-01,  9.26587911e-02],
       [ 2.67871458e-01,  2.76444823e-01],
       [ 8.31811371e-01, -2.13651262e-01],
       [-1.04798834e+00, -1.04068841e+00],
       [ 1.01979134e+00,  1.62420906e+00],
       [-1.40984978e-02,  2.45124620e+00],
       [-1.23596831e+00, -3.36175283e-01],
       [-1.08088483e-01,  1.01158895e+00],
       [-1.08088483e-01, -4.89330310e-01],
       [ 7.98914876e-02, -4.58699305e-01],
       [-1.08088483e-01, -1.01005740e+00],
       [-2.02078469e-01, -2.13651262e-01],
       [-1.32995829e+00, -5.50592321e-01],
       [ 9.25801356e-01, -7.03747347e-01],
       [ 1.86570121e+00, -1.83020257e-01],
       [ 2.67871458e-01, -1.52389251e-01],
       [ 6.43831400e-01, -8.26271368e-01],
       [ 3.61861444e-01, -1.10195042e+00],
       [ 2.

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
classifier = LogisticRegression(random_state=200)

In [24]:
classifier.fit(X_train,y_train)

C:\Users\SAIF04KHAN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\SAIF04KHAN\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=200, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [45]:
y_predict = classifier.predict(X_test)

In [66]:
z=classifier.predict([[24,100000]])

In [67]:
z

array([1], dtype=int64)

In [46]:
y_predict

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0], dtype=int64)

In [47]:
#confusion matrix or accuracy_score

from sklearn.metrics import accuracy_score

In [48]:
cm = accuracy_score(y_test,y_predict)*100

In [49]:
cm

84.5

In [50]:
import pickle

In [51]:
with open('model.pkl','wb') as f:
    pickle.dump(classifier,f)